---
- name: Merge user config with default config
  set_fact:
    - sshd_config: "{{ sshd_config_default + sshd_config }}"
  when: sshd_use_default
  tags:
    - configure

- name: Merge user config with os specific config
  set_fact:
    - sshd_config: "{{ sshd_config_default_dist + sshd_config }}"
  when: sshd_use_default_dist
  tags:
    - configure

- name: Set the listen v4 address to given interface address
  set_fact:
    - sshd_listen_address: "{{ sshd_listen_address }} + ['{{ hostvars[inventory_hostname]['ansible_' + sshd_listen_address_interface]['ipv4']['address'] }}']"
  when: sshd_config.ListenAddress == "" and hostvars[inventory_hostname]['ansible_' + sshd_listen_address_interface] is defined
  tags:
    - configure

- name: Set the listen v4 address to default address
  set_fact:
    - sshd_listen_address: "{{ sshd_listen_address }} + ['{{ ansible_default_ipv4.address }}']"
  when: sshd_config.ListenAddress == ""
  tags:
    - configure

- name: Set the listen v6 address to given interface address
  set_fact:
    - sshd_listen_address: "{{ sshd_listen_address }} + ['{{ hostvars[inventory_hostname]['ansible_' + sshd_listen_address_interface]['ipv6']['address'] }}']"
  when: sshd_config.ListenAddress is defined and sshd_config.ListenAddress == "" and hostvars[inventory_hostname]['ansible_' + sshd_listen_address_interface] is defined
  tags:
    - configure

- name: Set the listen v6 address to default address
  set_fact:
    - sshd_listen_address: "{{ sshd_listen_address }} + ['{{ ansible_default_ipv6.address }}']"
  when: sshd_config.ListenAddress is defined and sshd_config.ListenAddress == ""
  tags:
    - configure

- name: Set the listen address to Ansible default address
  set_fact:
    - sshd_listen_address:
  tags:
    - configure

- name: Update sshd_config
  template:
    src: "sshd_config.j2"
    dest: "{{ sshd_config_file }}"
    owner: "{{ sshd_config_owner }}"
    group: "{{ sshd_config_group }}"
    mode: "{{ sshd_config_mode }}"
    validate: "/usr/sbin/sshd -T -f %s"
  notify:
    - reload sshd
  tags:
    - configure
