---
- name: Add sshd_port to firewalld
  ansible.builtin.shell: firewall-cmd --permanent --zone="$(firewall-cmd --get-default-zone)" --add-port={{ sshd_config.Port|default('22') }}/tcp
  ignore_errors: true
  notify: reload firewalld
  when: has_firewalld

- name: Get iptables rules
  ansible.builtin.command: iptables -L --wait
  register: iptablesrules
  check_mode: false
  ignore_errors: true
  when: not has_firewalld and has_iptables

- name: Open sshd listen port with iptables
  ansible.builtin.command: "/sbin/iptables -I INPUT 1 -p tcp --dport {{ sshd_config.Port|default('22') }} -j ACCEPT -m comment --comment 'sshd'"
  ignore_errors: true
  when: not has_firewalld and has_iptables and "'sshd' not in iptablesrules.stdout"
  notify:
    - Save iptables rules
