---
- name: Add sshd_port to firewalld
  shell: firewall-cmd --permanent --zone="$(firewall-cmd --get-default-zone)" --add-port={{ sshd_port }}/tcp
  ignore_errors: true
  notify: reload firewalld
  when: has_firewalld

- name: Get iptables rules
  command: iptables -L --wait
  register: iptablesrules
  check_mode: no
  ignore_errors: true

- name: Open etcd client port with iptables
  command: "/sbin/iptables -I INPUT 1 -p tcp --dport {{ sshd_config.Port|default(22) }} -j ACCEPT -m comment --comment 'sshd'"
  ignore_errors: true
  when: "'sshd' not in iptablesrules.stdout"
  notify:
    - Save iptables rules
