---
- name: Install openssh-server package
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: "{{ item }}"
    state: latest
  with_items: "{{ sshd_packages }}"
  notify:
    - enable sshd
  tags: install
