---
- include: install.yml
  when: sshd_install

- name: Add/Remove sshd_config options
  lineinfile:
    dest: "{{ sshd_config_file }}"
    state: "{{ item.state|default('present') }}"
    regexp: '^{{ item.key }}.*'
    line: "{{ item.key }} {{ item.value }}"
    validate: "/usr/sbin/sshd -T -f %s"
  with_items: "{{ sshd_config }}"
  notify:
    - reload sshd
  tags:
    - configure

- include: selinux.yml

- include: firewall.yml
