---
- name: Set OS dependent variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}.yml"
        - default.yml

- ansible.builtin.include_tasks:
    file: install.yml
  when: sshd_packages_install

- ansible.builtin.include_tasks:
    file: configure.yml

- ansible.builtin.include_tasks:
    file: selinux.yml

- ansible.builtin.include_tasks:
    file: firewall.yml
  when: sshd_firewalling
