---
- name: Add ssh port to seport if selinux is enabled
  command: "semanage port -a -t ssh_port_t -p tcp {{ sshd_port }}"
  ignore_errors: yes
  when: 'ansible_selinux.status is defined and (ansible_selinux.status != "disabled" and ansible_selinux.status != "Missing selinux Python library")'
