---
# Handler to handle sshd notifications
- name: enable sshd
  service:
    name: sshd
    enabled: yes

- name: reload sshd
  service:
    name: sshd
    state: restarted

- name: reload firewalld
  command: firewall-cmd --reload
