---
# Handler to handle sshd notifications
- name: enable sshd
  service:
    name: "{{ sshd_service }}"
    enabled: yes

- name: reload sshd
  service:
    name: "{{ sshd_service }}"
    state: restarted

- name: reload firewalld
  ansible.builtin.command: firewall-cmd --reload

- name: Save iptables rules
  ansible.builtin.command: service iptables save
